---
- hosts: jenkins
- name: Install nginx
  hosts: jenkins
  gather_facts: true
  tags: [nginx]
  tasks:
  - name: Update the software package repository
    yum:
    update_cache: yes

- name: Install nginx
  package:
  name: “{{ item }}”
  state: latest
  with_items:
  - nginx

- name: Allow Nginx Full
  ufw:
  rule: allow
  name: Nginx Full
  state: enabled

- name: Allow Nginx Full
  ufw:
  rule: allow
  name: OpenSSH
  state: enabled

- name: Start nginx
  service:
  name: nginx
  state: started
  wait_for:
    port: 80
  
- name: "Habilitando o servico de NGINX"
  systemd: 
    enabled: true
    name: nginx
    state: restarted

